### ISSUE TITLE
name '__file__' is not defined

### ISSUE THREAD

**Issue by masong233** [Mabbs/socket-bbs#1]
如题试运行一下出现了这个错误，都已经在最首行了，咋还会这样呢

**Comment by Mabbs** [comment]
你的执行方式是什么？Python的版本号是什么？

**Comment by masong233** [comment]
Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 5.6.0
The server is running on this version of Python:
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]

Current Kernel Information:
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.
应该是3.7.0 我是直接run的，难道要用run test嘛

**Comment by Mabbs** [comment]
> Server Information: You are using Jupyter notebook.
> 
> The version of the notebook server is: 5.6.0 The server is running on this version of Python: Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
> 
> Current Kernel Information: Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] Type 'copyright', 'credits' or 'license' for more information IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help. 应该是3.7.0 我是直接run的，难道要用run test嘛

emmmm用jupyter应该运行不了吧，直接在控制台输入python3 main.py就行
